
kind: pipeline
name: 打包测试
​
steps:
- name: Maven编译
  image: maven:3.6.2-jdk-8
  volumes:
  - name: cache
    path: /root/.m2
  commands:
    - mvn clean install
  when:
    branch: master
    event: [ push ]

​