kind: pipeline
name: pipeline-example-maven


steps:
  - name: Maven
    image: maven:3-jdk-7
    volumes:
      - name: cache
        path: /root/.m2
    commands:
      - mvn clean install  -DskipTests -e -X

  - name: 构建镜像
    image: plugins/docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: hub.docker.com/repository/docker/heyanhui
      registry: hub.docker.com
      tags:
        - latest
        - '${DRONE_BRANCH}'
        - '${DRONE_BRANCH}-${DRONE_BUILD_NUMBER}'

volumes:
  - name: cache
    host:
      path: /tmp/cache/.m2
  - name: docker
    host:
      path: /var/run/docker.sock

trigger:
  branch:
  - master