
kind: pipeline
name: 打包测试
​
steps:
- name: Maven编译
  image: maven
  volumes:
  - name: cache
    path: /root/.m2
  commands:
    - mvn clean install
	
volumes:
- name: cache
  host:
    path: /tmp/cache/.m2
​
trigger:
  branch:
  - master
​