server:
  port: 80


#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.hyh.ease.rent.entity
  mapperLocations: classpath:mapper/*.xml


#开发配置
spring:
  #profiles: dev

  datasource:
    url: jdbc:mysql://10.145.240.45:3306/ctyun
    username: ctyun
    password: asdqe21eca_dasddsa
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
